apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-blue
  namespace: {{ .Values.projectNamespace }}
  labels:
    app: {{ .Values.projectName }}
    version: blue
    managed-by: helm
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.blue }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}
      version: blue
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}
        version: blue
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.targetPort }}"
        prometheus.io/path: "/metrics"
    spec:

      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}

      containers:
        - name: {{ .Values.projectName }}
          image: "{{ .Values.image.repository }}:blue"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 12 }}
          {{- end }}

          {{- if or .Values.secrets.name .Values.configMap.name }}
          envFrom:
            {{- if .Values.secrets.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
            {{- end }}
            {{- if .Values.configMap.name }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
          {{- end }}

          volumeMounts:
            - name: app-logs
              mountPath: /app/logs

          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
{{ toYaml .Values.healthCheck.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.healthCheck.readinessProbe | indent 12 }}
          {{- end }}

          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}

      volumes:
        - name: app-logs
          emptyDir: {}

      imagePullSecrets:
        - name: gitlab-registry-secret

      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}

      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}