projectName: "patient-web"
projectNamespace: "healthjini"

image:
  repository: "harbor.k8s.healthjini.ai:30443/production/patient_web"
  tag: "green"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: gitlab-registry-secret
env:
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"
secrets:
  name: healthjini-patient-secrets
host:
  - ip: 10.120.130.43
    domain: "backend.k8s.healthjini.ai" 

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "patient.k8s.healthjini.ai"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-tls
      hosts:
        - patient.k8s.healthjini.ai


healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: 8020
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: 8020
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

blueGreen:
  activeVersion: green
  scaleDownInactive: true
  inactiveReplicaCount: 0

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  workload-type: prodapp

securityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
