projectName: "frontend-web"
projectNamespace: "neuraiq"
image:
  repository: "docker.merai.app/production/frontend-web"
  tag: "dmz-green"
service:
  type: LoadBalancer
  port: 8011
  targetPort: 3000
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: 3000
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
ingress:
  enabled: false
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
nodeSelector:
  workload-type: prodapp