projectName: "centralized-backend"
projectNamespace: "healthjini"

image:
  repository: "harbor.k8s.healthjini.ai:30443/production/centralized_backend"
  tag: "green"

imagePullSecrets:
  - name: gitlab-registry-secret

service:
  type: ClusterIP
  port: 8005
  targetPort: 8080

ingress:
  enabled: true  
  className: "nginx"  # Use k8s ingress class
  hosts:
    - host: "backend.k8s.healthjini.ai"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-tls
      hosts:
        - backend.k8s.healthjini.ai

healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  workload-type: prodapp